# Generated by Django 4.2 on 2023-05-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
